export interface VocabularyWord {
  id: string;
  word: string; // English word in uppercase
  meaning: string; // Turkish translation
  pronunciation: string; // Simple pronunciation guide e.g. [brek-fıst]
  unitId: string;
  unitName: string;
  unitEmoji: string;
  sampleSentenceEn: string;
  sampleSentenceTr: string;
  questionSentence: string; // Sentence with "________"
  clue?: string; // Optional tip
  difficulty?: 'easy' | 'medium' | 'hard';
}

export interface Unit {
  id: string;
  title: string;
  description: string;
  emoji: string;
}

export const UNITS: Unit[] = [
  { id: 'all', title: 'Tüm 6. Sınıf Üniteleri', description: 'Müfredattaki tüm 6. sınıf temaları', emoji: '🌟' },
  { id: 'unit1', title: 'Life (Günlük Yaşam)', description: 'Günlük rutinler, okul ve saatler', emoji: '⏰' },
  { id: 'unit2', title: 'Yummy Breakfast (Kahvaltı)', description: 'Yiyecekler, içecekler ve tercihler', emoji: '🍳' },
  { id: 'unit3', title: 'Downtown (Şehir Hayatı)', description: 'Şehir, kasaba ve karşılaştırmalar', emoji: '🏙️' },
  { id: 'unit4', title: 'Weather and Emotions (Hava ve Duygular)', description: 'Hava durumu ve ruh halleri', emoji: '⛅' },
  { id: 'unit5', title: 'At the Fair (Lunapark)', description: 'Lunapark oyuncakları ve duygular', emoji: '🎡' },
  { id: 'unit6', title: 'Occupations (Meslekler)', description: 'Meslekler, işler ve görevler', emoji: '👨‍⚕️' },
  { id: 'unit7', title: 'Holidays (Tatil)', description: 'Tatil aktiviteleri ve geçmiş zaman', emoji: '🏖️' },
  { id: 'unit8', title: 'Bookworms (Kitap Kurtları)', description: 'Kitaplar, kütüphane ve yer edatları', emoji: '📚' },
  { id: 'unit9', title: 'Saving the Planet (Gezegenimizi Koruma)', description: 'Çevre, geri dönüşüm ve doğa', emoji: '🌱' },
  { id: 'unit10', title: 'Democracy (Demokrasi)', description: 'Seçimler, oy verme ve kurallar', emoji: '🗳️' },
];

export const VOCABULARY_LIST: VocabularyWord[] = [
  // Unit 1: Life / Daily Routine
  {
    id: 'u1-1',
    word: 'BREAKFAST',
    meaning: 'Kahvaltı',
    pronunciation: '[brek-fıst]',
    unitId: 'unit1',
    unitName: 'Unit 1: Life',
    unitEmoji: '⏰',
    sampleSentenceEn: 'I have a big breakfast with my family every Sunday.',
    sampleSentenceTr: 'Her pazar ailemle birlikte büyük bir kahvaltı yaparım.',
    questionSentence: 'I eat eggs, cheese and olives for ________ every morning.',
    clue: 'Günün ilk ve en önemli öğünü',
    difficulty: 'easy',
  },
  {
    id: 'u1-2',
    word: 'ROUTINE',
    meaning: 'Günlük düzen / Rutin',
    pronunciation: '[ru-tiyn]',
    unitId: 'unit1',
    unitName: 'Unit 1: Life',
    unitEmoji: '⏰',
    sampleSentenceEn: 'Brushing teeth before sleeping is my daily routine.',
    sampleSentenceTr: 'Uyumadan önce diş fırçalamak benim günlük rutinimdir.',
    questionSentence: 'Doing homework after school is part of my daily ________.',
    clue: 'Her gün düzenli yapılan işler',
    difficulty: 'medium',
  },
  {
    id: 'u1-3',
    word: 'ATTEND',
    meaning: 'Katılmak (derse/kursa)',
    pronunciation: '[ı-tend]',
    unitId: 'unit1',
    unitName: 'Unit 1: Life',
    unitEmoji: '⏰',
    sampleSentenceEn: 'Mert attends a chess club after school on Fridays.',
    sampleSentenceTr: 'Mert cuma günleri okuldan sonra satranç kulübüne katılır.',
    questionSentence: 'I want to ________ the traditional folk dance course.',
    clue: 'Bir etkinliğe ya da kursa gitmek/iştirak etmek',
    difficulty: 'medium',
  },
  {
    id: 'u1-4',
    word: 'DIARY',
    meaning: 'Günlük',
    pronunciation: '[day-rı]',
    unitId: 'unit1',
    unitName: 'Unit 1: Life',
    unitEmoji: '⏰',
    sampleSentenceEn: 'Zeynep writes in her diary every evening before bed.',
    sampleSentenceTr: 'Zeynep her akşam yatmadan önce günlüğüne yazar.',
    questionSentence: 'I write my secret thoughts in my personal ________.',
    clue: 'Günün anılarını yazdığımız defter',
    difficulty: 'easy',
  },
  {
    id: 'u1-5',
    word: 'NAP',
    meaning: 'Kısa uyku / Şekerleme',
    pronunciation: '[nep]',
    unitId: 'unit1',
    unitName: 'Unit 1: Life',
    unitEmoji: '⏰',
    sampleSentenceEn: 'My grandfather takes a nap after lunch.',
    sampleSentenceTr: 'Büyükbabam öğle yemeğinden sonra şekerleme yapar.',
    questionSentence: 'I feel very tired, so I will take a short ________ for thirty minutes.',
    clue: 'Gündüzleri yapılan kısa dinlenme uykusu',
    difficulty: 'easy',
  },

  // Unit 2: Yummy Breakfast
  {
    id: 'u2-1',
    word: 'DELICIOUS',
    meaning: 'Lezzetli / Nefis',
    pronunciation: '[dı-li-şıs]',
    unitId: 'unit2',
    unitName: 'Unit 2: Yummy Breakfast',
    unitEmoji: '🍳',
    sampleSentenceEn: 'My mother makes delicious pancakes with honey.',
    sampleSentenceTr: 'Annem ballı çok lezzetli krepler yapar.',
    questionSentence: 'This homemade strawberry jam tastes really ________.',
    clue: 'Yemek tadı harika olduğunda söylenen kelime',
    difficulty: 'easy',
  },
  {
    id: 'u2-2',
    word: 'NUTRITIOUS',
    meaning: 'Besleyici / Faydalı',
    pronunciation: '[nu-tri-şıs]',
    unitId: 'unit2',
    unitName: 'Unit 2: Yummy Breakfast',
    unitEmoji: '🍳',
    sampleSentenceEn: 'Milk, eggs and honey are very nutritious foods.',
    sampleSentenceTr: 'Süt, yumurta ve bal çok besleyici gıdalardır.',
    questionSentence: 'Eating fresh vegetables and drinking fruit juice is very ________.',
    clue: 'Vücuda sağlık ve enerji katan gıdalar',
    difficulty: 'hard',
  },
  {
    id: 'u2-3',
    word: 'CROISSANT',
    meaning: 'Kruvasan (Ay çöreği)',
    pronunciation: '[krua-san]',
    unitId: 'unit2',
    unitName: 'Unit 2: Yummy Breakfast',
    unitEmoji: '🍳',
    sampleSentenceEn: 'French people often have a croissant and coffee for breakfast.',
    sampleSentenceTr: 'Fransızlar kahvaltıda genellikle kruvasan ve kahve tüketirler.',
    questionSentence: 'I like spreading chocolate cream inside a warm ________.',
    clue: 'Ay şeklinde Fransız hamur işi',
    difficulty: 'medium',
  },
  {
    id: 'u2-4',
    word: 'CUCUMBER',
    meaning: 'Salatalık',
    pronunciation: '[kju-kam-bır]',
    unitId: 'unit2',
    unitName: 'Unit 2: Yummy Breakfast',
    unitEmoji: '🍳',
    sampleSentenceEn: 'Turkish breakfast always includes sliced tomatoes and cucumber.',
    sampleSentenceTr: 'Türk kahvaltısında her zaman dilimlenmiş domates ve salatalık bulunur.',
    questionSentence: 'Can you slice some tomatoes and ________ for the salad?',
    clue: 'Yeşil, sulu, kahvaltı ve salataların vazgeçilmezi',
    difficulty: 'easy',
  },
  {
    id: 'u2-5',
    word: 'PREFER',
    meaning: 'Tercih etmek',
    pronunciation: '[pri-för]',
    unitId: 'unit2',
    unitName: 'Unit 2: Yummy Breakfast',
    unitEmoji: '🍳',
    sampleSentenceEn: 'I prefer drinking orange juice to drinking fizzy drinks.',
    sampleSentenceTr: 'Portakal suyu içmeyi gazlı içecek içmeye tercih ederim.',
    questionSentence: 'Do you ________ hot chocolate or warm milk in the morning?',
    clue: 'Bir şeyi başka bir şeye yeğlemek',
    difficulty: 'medium',
  },

  // Unit 3: Downtown
  {
    id: 'u3-1',
    word: 'DOWNTOWN',
    meaning: 'Şehir merkezi',
    pronunciation: '[dawn-tavn]',
    unitId: 'unit3',
    unitName: 'Unit 3: Downtown',
    unitEmoji: '🏙️',
    sampleSentenceEn: 'There are tall buildings and shopping malls downtown.',
    sampleSentenceTr: 'Şehir merkezinde yüksek binalar ve alışveriş merkezleri vardır.',
    questionSentence: 'The streets are very crowded in the ________ during rush hour.',
    clue: 'Şehrin en hareketli ve kalabalık çarşı merkezi',
    difficulty: 'medium',
  },
  {
    id: 'u3-2',
    word: 'CROWDED',
    meaning: 'Kalabalık',
    pronunciation: '[krav-dıd]',
    unitId: 'unit3',
    unitName: 'Unit 3: Downtown',
    unitEmoji: '🏙️',
    sampleSentenceEn: 'The metro station is very crowded on Monday mornings.',
    sampleSentenceTr: 'Metro istasyonu pazartesi sabahları çok kalabalıktır.',
    questionSentence: 'Big cities are much more ________ than small quiet villages.',
    clue: 'İçinde çok fazla insanın bulunduğu yer',
    difficulty: 'easy',
  },
  {
    id: 'u3-3',
    word: 'SKYSCRAPER',
    meaning: 'Gökdelen',
    pronunciation: '[skay-skrey-pır]',
    unitId: 'unit3',
    unitName: 'Unit 3: Downtown',
    unitEmoji: '🏙️',
    sampleSentenceEn: 'You can see the whole city from the top of the skyscraper.',
    sampleSentenceTr: 'Gökdelenin tepesinden tüm şehri görebilirsin.',
    questionSentence: 'That modern ________ has more than sixty floors.',
    clue: 'Gökyüzüne uzanan çok katlı devasa bina',
    difficulty: 'medium',
  },
  {
    id: 'u3-4',
    word: 'TRAFFIC JAM',
    meaning: 'Trafik sıkışıklığı',
    pronunciation: '[tre-fik cem]',
    unitId: 'unit3',
    unitName: 'Unit 3: Downtown',
    unitEmoji: '🏙️',
    sampleSentenceEn: 'We were late for school because of a heavy traffic jam.',
    sampleSentenceTr: 'Yoğun trafik sıkışıklığı yüzünden okula geç kaldık.',
    questionSentence: 'There is a long line of cars stuck in a ________ on the bridge.',
    clue: 'Araçların ilerleyemediği yoğun yol durumu',
    difficulty: 'medium',
  },
  {
    id: 'u3-5',
    word: 'KIOSK',
    meaning: 'Büfe / Gazete kulübesi',
    pronunciation: '[ki-osk]',
    unitId: 'unit3',
    unitName: 'Unit 3: Downtown',
    unitEmoji: '🏙️',
    sampleSentenceEn: 'My father buys a newspaper from the street kiosk every day.',
    sampleSentenceTr: 'Babam her gün sokaktaki büfeden gazete satın alır.',
    questionSentence: 'Let\'s buy some bottled water and bus tickets from the corner ________.',
    clue: 'Sokakta gazete, su, dergi satılan küçük dükkan',
    difficulty: 'easy',
  },

  // Unit 4: Weather and Emotions
  {
    id: 'u4-1',
    word: 'LIGHTNING',
    meaning: 'Şimşek / Yıldırım',
    pronunciation: '[layt-ning]',
    unitId: 'unit4',
    unitName: 'Unit 4: Weather & Emotions',
    unitEmoji: '⛅',
    sampleSentenceEn: 'We saw a bright flash of lightning during the storm.',
    sampleSentenceTr: 'Fırtına sırasında parlak bir şimşek çakması gördük.',
    questionSentence: 'Thunder and ________ scared the little puppy in the garden.',
    clue: 'Gök gürültüsünden önce gökte parlayan ışık',
    difficulty: 'medium',
  },
  {
    id: 'u4-2',
    word: 'ANXIOUS',
    meaning: 'Endişeli / Kaygılı',
    pronunciation: '[enk-şıs]',
    unitId: 'unit4',
    unitName: 'Unit 4: Weather & Emotions',
    unitEmoji: '⛅',
    sampleSentenceEn: 'Selin feels anxious when there is a stormy weather.',
    sampleSentenceTr: 'Selin fırtınalı bir hava olduğunda endişeli hisseder.',
    questionSentence: 'I feel very ________ before my big English exam.',
    clue: 'Huzursuz, tedirgin ve kaygılı ruh hali',
    difficulty: 'hard',
  },
  {
    id: 'u4-3',
    word: 'FREEZING',
    meaning: 'Dondurucu soğuk',
    pronunciation: '[frii-zing]',
    unitId: 'unit4',
    unitName: 'Unit 4: Weather & Emotions',
    unitEmoji: '⛅',
    sampleSentenceEn: 'Wear your heavy coat because it is freezing outside today.',
    sampleSentenceTr: 'Bugün dışarısı dondurucu soğuk olduğu için kalın montunu giy.',
    questionSentence: 'The temperature is minus ten degrees Celsius; it is completely ________.',
    clue: 'Sıfırın altında, buz kestiren hava',
    difficulty: 'easy',
  },
  {
    id: 'u4-4',
    word: 'FABULOUS',
    meaning: 'Harika / Muhteşem',
    pronunciation: '[feb-yı-lıs]',
    unitId: 'unit4',
    unitName: 'Unit 4: Weather & Emotions',
    unitEmoji: '⛅',
    sampleSentenceEn: 'We had a fabulous time at the seaside in sunny weather.',
    sampleSentenceTr: 'Güneşli havada deniz kenarında harika bir zaman geçirdik.',
    questionSentence: 'The sunny weather makes me feel cheerful and ________.',
    clue: 'Çok güzel, kusursuz ve sevindirici',
    difficulty: 'medium',
  },
  {
    id: 'u4-5',
    word: 'HAILING',
    meaning: 'Dolu yağıyor',
    pronunciation: '[hey-ling]',
    unitId: 'unit4',
    unitName: 'Unit 4: Weather & Emotions',
    unitEmoji: '⛅',
    sampleSentenceEn: 'Look out of the window! Small ice balls are falling, it is hailing.',
    sampleSentenceTr: 'Pencereden dışarı bak! Küçük buz taneleri düşüyor, dolu yağıyor.',
    questionSentence: 'Protect your car because it started ________ heavily.',
    clue: 'Gökten buz taneciklerinin düşmesi',
    difficulty: 'medium',
  },

  // Unit 5: At the Fair
  {
    id: 'u5-1',
    word: 'ROLLER COASTER',
    meaning: 'Hız treni',
    pronunciation: '[rol-lır kos-tır]',
    unitId: 'unit5',
    unitName: 'Unit 5: At the Fair',
    unitEmoji: '🎡',
    sampleSentenceEn: 'The roller coaster is the most exciting ride at the amusement park.',
    sampleSentenceTr: 'Hız treni lunaparktaki en heyecan verici oyuncaktır.',
    questionSentence: 'Riding the fast ________ was terrifying but so fun!',
    clue: 'Raylar üzerinde hızla dönen lunapark aracı',
    difficulty: 'easy',
  },
  {
    id: 'u5-2',
    word: 'FERRIS WHEEL',
    meaning: 'Dönme dolap',
    pronunciation: '[fe-ris wiil]',
    unitId: 'unit5',
    unitName: 'Unit 5: At the Fair',
    unitEmoji: '🎡',
    sampleSentenceEn: 'You can see the carnival lights from the giant Ferris wheel.',
    sampleSentenceTr: 'Dev dönme dolaptan karnaval ışıklarını görebilirsin.',
    questionSentence: 'My little sister loves watching the scenery from the big ________.',
    clue: 'Dairesel dönen devasa lunapark çarkı',
    difficulty: 'medium',
  },
  {
    id: 'u5-3',
    word: 'BUMPER CARS',
    meaning: 'Çarpışan arabalar',
    pronunciation: '[bam-pır karz]',
    unitId: 'unit5',
    unitName: 'Unit 5: At the Fair',
    unitEmoji: '🎡',
    sampleSentenceEn: 'Crashing into my friend\'s car in the bumper cars made us laugh.',
    sampleSentenceTr: 'Çarpışan arabalarda arkadaşımın arabasına çarpmak bizi güldürdü.',
    questionSentence: 'Kids always race to drive the colourful ________ at the fair.',
    clue: 'Birbirine çarparak sürülen eğlence arabaları',
    difficulty: 'easy',
  },
  {
    id: 'u5-4',
    word: 'GHOST TRAIN',
    meaning: 'Korku treni',
    pronunciation: '[gost treyn]',
    unitId: 'unit5',
    unitName: 'Unit 5: At the Fair',
    unitEmoji: '🎡',
    sampleSentenceEn: 'I screamed when a scary monster appeared in the ghost train.',
    sampleSentenceTr: 'Korku treninde ürkütücü bir canavar belirdiğinde çığlık attım.',
    questionSentence: 'The dark tunnel of the ________ was very frightening.',
    clue: 'Karanlıkta korkunç sesler ve figürler içeren tren',
    difficulty: 'easy',
  },
  {
    id: 'u5-5',
    word: 'THRILLING',
    meaning: 'Heyecan verici / Nefes kesici',
    pronunciation: '[thril-ling]',
    unitId: 'unit5',
    unitName: 'Unit 5: At the Fair',
    unitEmoji: '🎡',
    sampleSentenceEn: 'Flying swings gave us a thrilling experience.',
    sampleSentenceTr: 'Uçan salıncaklar bize heyecan verici bir deneyim yaşattı.',
    questionSentence: 'I think amusement park rides are totally ________.',
    clue: 'Kalp atışlarını hızlandıran coşkulu durum',
    difficulty: 'hard',
  },

  // Unit 6: Occupations
  {
    id: 'u6-1',
    word: 'OCCUPATION',
    meaning: 'Meslek',
    pronunciation: '[ak-yu-pey-şın]',
    unitId: 'unit6',
    unitName: 'Unit 6: Occupations',
    unitEmoji: '👨‍⚕️',
    sampleSentenceEn: 'What is your father\'s occupation? - He is an architect.',
    sampleSentenceTr: 'Babanın mesleği nedir? - O bir mimardır.',
    questionSentence: 'Teaching is a very respectable and rewarding ________.',
    clue: 'İnsanların para kazanmak için yaptığı uzmanlık işi',
    difficulty: 'medium',
  },
  {
    id: 'u6-2',
    word: 'ARCHITECT',
    meaning: 'Mimar',
    pronunciation: '[aar-kı-tekt]',
    unitId: 'unit6',
    unitName: 'Unit 6: Occupations',
    unitEmoji: '👨‍⚕️',
    sampleSentenceEn: 'An architect draws building plans and designs new houses.',
    sampleSentenceTr: 'Bir mimar bina planları çizer ve yeni evler tasarlar.',
    questionSentence: 'Sinan is an ________; he designs modern shopping centers and hospitals.',
    clue: 'Binaları ve yapıları tasarlayan uzman',
    difficulty: 'medium',
  },
  {
    id: 'u6-3',
    word: 'TAILOR',
    meaning: 'Terzi',
    pronunciation: '[tey-lır]',
    unitId: 'unit6',
    unitName: 'Unit 6: Occupations',
    unitEmoji: '👨‍⚕️',
    sampleSentenceEn: 'The tailor cuts fabrics and sews nice suits.',
    sampleSentenceTr: 'Terzi kumaşları keser ve güzel takım elbiseler diker.',
    questionSentence: 'I took my torn trousers to the local ________ to be repaired.',
    clue: 'Kıyafet diken ve tamir eden meslek sahibi',
    difficulty: 'easy',
  },
  {
    id: 'u6-4',
    word: 'MECHANIC',
    meaning: 'Oto tamircisi / Motor ustası',
    pronunciation: '[mı-ke-nik]',
    unitId: 'unit6',
    unitName: 'Unit 6: Occupations',
    unitEmoji: '👨‍⚕️',
    sampleSentenceEn: 'The mechanic repaired our broken car engine in two hours.',
    sampleSentenceTr: 'Tamirci bozulan araba motorumuzu iki saatte tamir etti.',
    questionSentence: 'When our vehicle broke down on the road, we called a ________.',
    clue: 'Bozuk araçları ve motorları tamir eden kişi',
    difficulty: 'medium',
  },
  {
    id: 'u6-5',
    word: 'RETIRE',
    meaning: 'Emekli olmak',
    pronunciation: '[rı-tayr]',
    unitId: 'unit6',
    unitName: 'Unit 6: Occupations',
    unitEmoji: '👨‍⚕️',
    sampleSentenceEn: 'My grandfather will retire next month after working for thirty years.',
    sampleSentenceTr: 'Dedem otuz yıl çalıştıktan sonra gelecek ay emekli olacak.',
    questionSentence: 'She worked as a doctor for 40 years before deciding to ________.',
    clue: 'Çalışma yaşını tamamlayıp iş hayatını sonlandırmak',
    difficulty: 'medium',
  },

  // Unit 7: Holidays
  {
    id: 'u7-1',
    word: 'SIGHTSEEING',
    meaning: 'Turistik yerleri gezme',
    pronunciation: '[sayt-sii-ing]',
    unitId: 'unit7',
    unitName: 'Unit 7: Holidays',
    unitEmoji: '🏖️',
    sampleSentenceEn: 'We went sightseeing around ancient monuments in Rome.',
    sampleSentenceTr: 'Roma\'daki tarihi anıtların etrafında turistik geziye çıktık.',
    questionSentence: 'Taking a bus tour is the best way to do ________ in Istanbul.',
    clue: 'Tarihi ve turistik güzellikleri görme turu',
    difficulty: 'medium',
  },
  {
    id: 'u7-2',
    word: 'SEASIDE',
    meaning: 'Deniz kenarı / Sahil',
    pronunciation: '[sii-sayd]',
    unitId: 'unit7',
    unitName: 'Unit 7: Holidays',
    unitEmoji: '🏖️',
    sampleSentenceEn: 'We built huge sandcastles on the seaside.',
    sampleSentenceTr: 'Deniz kenarında devasa kumdan kaleler yaptık.',
    questionSentence: 'I enjoy walking barefoot on the sandy ________.',
    clue: 'Denizin karayla buluştuğu kıyı bölgesi',
    difficulty: 'easy',
  },
  {
    id: 'u7-3',
    word: 'SOUVENIR',
    meaning: 'Hediyelik eşya / Hatıra',
    pronunciation: '[suu-vı-niyr]',
    unitId: 'unit7',
    unitName: 'Unit 7: Holidays',
    unitEmoji: '🏖️',
    sampleSentenceEn: 'I bought a miniature clock tower as a souvenir from Izmir.',
    sampleSentenceTr: 'İzmir\'den hatıra olarak minyatür bir saat kulesi aldım.',
    questionSentence: 'Don\'t forget to buy a cute ________ for your grandparents from Antalya.',
    clue: 'Gidilen yerden anı kalması için alınan hatıra eşya',
    difficulty: 'medium',
  },
  {
    id: 'u7-4',
    word: 'CAMPING',
    meaning: 'Kamp yapma',
    pronunciation: '[kem-ping]',
    unitId: 'unit7',
    unitName: 'Unit 7: Holidays',
    unitEmoji: '🏖️',
    sampleSentenceEn: 'We set up our green tent near the forest lake while camping.',
    sampleSentenceTr: 'Kamp yaparken orman gölünün yanına yeşil çadırımızı kurduk.',
    questionSentence: 'Sleeping in a sleeping bag under the stars is what makes ________ exciting.',
    clue: 'Doğada çadır kurarak yapılan konaklama',
    difficulty: 'easy',
  },
  {
    id: 'u7-5',
    word: 'SCUBA DIVING',
    meaning: 'Tüplü dalış',
    pronunciation: '[sku-ba day-ving]',
    unitId: 'unit7',
    unitName: 'Unit 7: Holidays',
    unitEmoji: '🏖️',
    sampleSentenceEn: 'We saw colorful fish and sea turtles while scuba diving in Kas.',
    sampleSentenceTr: 'Kaş\'ta tüplü dalış yaparken renkli balıklar ve deniz kaplumbağaları gördük.',
    questionSentence: 'You need an oxygen tank and mask for ________ under the sea.',
    clue: 'Oksijen tüpüyle suyun derinliklerine inme sporu',
    difficulty: 'hard',
  },

  // Unit 8: Bookworms
  {
    id: 'u8-1',
    word: 'BOOKSHELF',
    meaning: 'Kitaplık rafı',
    pronunciation: '[buk-şelf]',
    unitId: 'unit8',
    unitName: 'Unit 8: Bookworms',
    unitEmoji: '📚',
    sampleSentenceEn: 'She arranged all novel series neatly on the bookshelf.',
    sampleSentenceTr: 'Tüm roman serilerini kitaplık rafına düzenlice dizdi.',
    questionSentence: 'Please take the red encyclopedia from the top ________.',
    clue: 'Kitapların dizildiği ahşap raf',
    difficulty: 'easy',
  },
  {
    id: 'u8-2',
    word: 'BORROW',
    meaning: 'Ödünç almak',
    pronunciation: '[bo-row]',
    unitId: 'unit8',
    unitName: 'Unit 8: Bookworms',
    unitEmoji: '📚',
    sampleSentenceEn: 'You can borrow up to three books from the school library.',
    sampleSentenceTr: 'Okul kütüphanesinden üçe kadar kitap ödünç alabilirsin.',
    questionSentence: 'Can I ________ your dictionary for ten minutes?',
    clue: 'Geri vermek şartıyla bir eşyayı geçici olarak almak',
    difficulty: 'medium',
  },
  {
    id: 'u8-3',
    word: 'AUTHOR',
    meaning: 'Yazar',
    pronunciation: '[oo-thır]',
    unitId: 'unit8',
    unitName: 'Unit 8: Bookworms',
    unitEmoji: '📚',
    sampleSentenceEn: 'J.K. Rowling is the famous author of the Harry Potter books.',
    sampleSentenceTr: 'J.K. Rowling, Harry Potter kitaplarının ünlü yazarıdır.',
    questionSentence: 'Who is the ________ of this fascinating mystery story?',
    clue: 'Kitapları, hikayeleri ve romanları yazan kişi',
    difficulty: 'easy',
  },
  {
    id: 'u8-4',
    word: 'DICTIONARY',
    meaning: 'Sözlük',
    pronunciation: '[dik-şı-ne-ri]',
    unitId: 'unit8',
    unitName: 'Unit 8: Bookworms',
    unitEmoji: '📚',
    sampleSentenceEn: 'Look up unknown words in an English-Turkish dictionary.',
    sampleSentenceTr: 'Bilinmeyen kelimelere İngilizce-Türkçe sözlükten bak.',
    questionSentence: 'I always keep a pocket ________ on my desk while studying English.',
    clue: 'Kelimelerin anlamlarını barındıran rehber kitap',
    difficulty: 'easy',
  },
  {
    id: 'u8-5',
    word: 'LITERATURE',
    meaning: 'Edebiyat',
    pronunciation: '[lit-rı-çır]',
    unitId: 'unit8',
    unitName: 'Unit 8: Bookworms',
    unitEmoji: '📚',
    sampleSentenceEn: 'Reading classic Turkish literature improves our vocabulary.',
    sampleSentenceTr: 'Klasik Türk edebiyatı okumak kelime haznemizi geliştirir.',
    questionSentence: 'Poems and novels are important parts of world ________.',
    clue: 'Şiir, roman, tiyatro gibi sanatsal yazı türlerinin tümü',
    difficulty: 'hard',
  },

  // Unit 9: Saving the Planet
  {
    id: 'u9-1',
    word: 'POLLUTION',
    meaning: 'Kirlilik (Çevre kirliliği)',
    pronunciation: '[pı-luu-şın]',
    unitId: 'unit9',
    unitName: 'Unit 9: Saving the Planet',
    unitEmoji: '🌱',
    sampleSentenceEn: 'Air pollution harms human health and nature.',
    sampleSentenceTr: 'Hava kirliliği insan sağlığına ve doğaya zarar verir.',
    questionSentence: 'Throwing trash on streets causes severe soil and water ________.',
    clue: 'Çevrenin çöp ve zehirli gazlarla bozulması durumu',
    difficulty: 'medium',
  },
  {
    id: 'u9-2',
    word: 'RECYCLE',
    meaning: 'Geri dönüştürmek',
    pronunciation: '[ri-say-kıl]',
    unitId: 'unit9',
    unitName: 'Unit 9: Saving the Planet',
    unitEmoji: '🌱',
    sampleSentenceEn: 'We should recycle glass bottles, plastic bags and paper.',
    sampleSentenceTr: 'Cam şişeleri, plastik poşetleri ve kağıtları geri dönüştürmeliyiz.',
    questionSentence: 'Put your empty soda cans into the green ________ bin.',
    clue: 'Atıkları yeniden kullanılabilir hale getirmek',
    difficulty: 'easy',
  },
  {
    id: 'u9-3',
    word: 'SAVE',
    meaning: 'Tasarruf etmek / Kurtarmak',
    pronunciation: '[seyv]',
    unitId: 'unit9',
    unitName: 'Unit 9: Saving the Planet',
    unitEmoji: '🌱',
    sampleSentenceEn: 'Turn off the tap to save water while brushing your teeth.',
    sampleSentenceTr: 'Dişlerini fırçalarken su tasarrufu yapmak için musluğu kapat.',
    questionSentence: 'We can ________ electricity by switching off unnecessary lights.',
    clue: 'Kaynakları israf etmeden idareli kullanmak',
    difficulty: 'easy',
  },
  {
    id: 'u9-4',
    word: 'LITTER',
    meaning: 'Çöp atmak / Yerlere atılan çöp',
    pronunciation: '[li-tır]',
    unitId: 'unit9',
    unitName: 'Unit 9: Saving the Planet',
    unitEmoji: '🌱',
    sampleSentenceEn: 'Do not drop litter in public parks and school gardens.',
    sampleSentenceTr: 'Halka açık parklara ve okul bahçelerine çöp atmayınız.',
    questionSentence: 'It is strictly forbidden to ________ on the grass in the forest.',
    clue: 'Yere rastgele fırlatılan atıklar',
    difficulty: 'easy',
  },
  {
    id: 'u9-5',
    word: 'ENVIRONMENT',
    meaning: 'Çevre / Doğa',
    pronunciation: '[en-vay-rın-mınt]',
    unitId: 'unit9',
    unitName: 'Unit 9: Saving the Planet',
    unitEmoji: '🌱',
    sampleSentenceEn: 'Planting trees helps protect our environment.',
    sampleSentenceTr: 'Ağaç dikmek çevremizi korumaya yardımcı olur.',
    questionSentence: 'We all have a responsibility to keep our natural ________ clean.',
    clue: 'Canlıların içinde yaşadığı doğal ortam',
    difficulty: 'hard',
  },

  // Unit 10: Democracy
  {
    id: 'u10-1',
    word: 'CANDIDATE',
    meaning: 'Aday (Seçim adayı)',
    pronunciation: '[ken-dı-deyt]',
    unitId: 'unit10',
    unitName: 'Unit 10: Democracy',
    unitEmoji: '🗳️',
    sampleSentenceEn: 'Ahmet is a candidate for the school president election.',
    sampleSentenceTr: 'Ahmet okul başkanlığı seçimi için bir adaydır.',
    questionSentence: 'Each class ________ prepared a poster to explain their campaign.',
    clue: 'Seçimlerde bir göreve seçilmek isteyen kişi',
    difficulty: 'medium',
  },
  {
    id: 'u10-2',
    word: 'VOTE',
    meaning: 'Oy vermek / Oy',
    pronunciation: '[vot]',
    unitId: 'unit10',
    unitName: 'Unit 10: Democracy',
    unitEmoji: '🗳️',
    sampleSentenceEn: 'Every citizen has the right to vote in democratic elections.',
    sampleSentenceTr: 'Her vatandaşın demokratik seçimlerde oy verme hakkı vardır.',
    questionSentence: 'Cast your ________ into the ballot box secretly.',
    clue: 'Seçimlerde tercihimizi belirten pusula veya eylem',
    difficulty: 'easy',
  },
  {
    id: 'u10-3',
    word: 'BALLOT BOX',
    meaning: 'Seçim sandığı',
    pronunciation: '[be-lıt baks]',
    unitId: 'unit10',
    unitName: 'Unit 10: Democracy',
    unitEmoji: '🗳️',
    sampleSentenceEn: 'Students dropped their folded papers into the ballot box.',
    sampleSentenceTr: 'Öğrenciler katlanmış kağıtlarını seçim sandığına attılar.',
    questionSentence: 'The teacher opened the ________ to count all the votes.',
    clue: 'Oyların içine atıldığı kilitli kutu',
    difficulty: 'medium',
  },
  {
    id: 'u10-4',
    word: 'EQUAL',
    meaning: 'Eşit',
    pronunciation: '[ii-kwıl]',
    unitId: 'unit10',
    unitName: 'Unit 10: Democracy',
    unitEmoji: '🗳️',
    sampleSentenceEn: 'All human beings are born free and equal in rights.',
    sampleSentenceTr: 'Tüm insanlar haklar bakımından özgür ve eşit doğarlar.',
    questionSentence: 'In our classroom, boys and girls have ________ chances and rights.',
    clue: 'Aynı değere ve hakka sahip olan',
    difficulty: 'easy',
  },
  {
    id: 'u10-5',
    word: 'PRESIDENT',
    meaning: 'Başkan',
    pronunciation: '[pre-zı-dınt]',
    unitId: 'unit10',
    unitName: 'Unit 10: Democracy',
    unitEmoji: '🗳️',
    sampleSentenceEn: 'Elif won the election and became our new class president.',
    sampleSentenceTr: 'Elif seçimi kazandı ve yeni sınıf başkanımız oldu.',
    questionSentence: 'The school ________ promised to organize a sports tournament.',
    clue: 'Topluluğu yönetmek üzere seçilen lider',
    difficulty: 'easy',
  }
];

export const MOTIVATION_MESSAGES = [
  '🎉 Harikasın! Aynen böyle devam et!',
  '🌟 Süper! 6. sınıf kelime bilgin harika gelişiyor!',
  '👏 Aferin! Doğru cevap, yıldızı kaptın!',
  '🚀 Müthişsin! Bir adım daha ileri gittin!',
  '💯 Tam isabet! Çok başarılı bir cevap!',
  '✨ Bravo! İngilizce hafızan çok kuvvetli!',
];

export const GENTLE_CORRECTIONS = [
  '💪 Çok yaklaştın! Merak etme, tekrar ederek öğreneceksin.',
  '🌱 Yanılmak öğrenmenin ilk adımıdır! Doğru cevabı aklına yazalım.',
  '🧐 Güzel bir denemeydi! Doğru cevabı birlikte inceleyelim.',
  '🎯 Sorun değil, şimdi bu kelimeyi çok daha iyi hatırlayacaksın.',
];
